'use client';

import { useState } from 'react';
import { dataStore } from '@/lib/dataStore';
import { Chapter, Scene } from '@/types';

export default function WritingAssistantPage() {
  const chapters = dataStore.getAllChapters();
  const [selectedChapter, setSelectedChapter] = useState<string>('');
  const [selectedScene, setSelectedScene] = useState<string>('');
  const [scenes, setScenes] = useState<Scene[]>([]);
  const [assistantType, setAssistantType] = useState<'continue' | 'revise' | 'suggest' | 'analyze'>('continue');
  const [customPrompt, setCustomPrompt] = useState('');
  const [response, setResponse] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleChapterSelect = (chapterId: string) => {
    setSelectedChapter(chapterId);
    const chapterScenes = dataStore.getScenesByChapter(chapterId);
    setScenes(chapterScenes);
    setSelectedScene('');
  };

  const handleGetAssistance = async () => {
    setIsLoading(true);
    setResponse('');

    // Build context
    const scene = selectedScene ? dataStore.getScene(selectedScene) : null;
    const chapter = selectedChapter ? dataStore.getChapter(selectedChapter) : null;

    // Simulate LLM response (in real implementation, would call MCP server)
    setTimeout(() => {
      let mockResponse = '';
      
      if (assistantType === 'continue') {
        mockResponse = `**Continuing from ${scene?.title || 'selected scene'}:**\n\nThis is where the LLM would continue writing based on the current scene context, maintaining character voices, plot threads, and story tone.\n\nThe MCP server would provide:\n- Previous scene content\n- Active character profiles\n- Current plot threads\n- Story notes and world-building details\n\nConnect this to Claude, GPT-4, or another LLM via the MCP protocol to get actual writing assistance.`;
      } else if (assistantType === 'revise') {
        mockResponse = `**Revision Suggestions for ${scene?.title || 'selected scene'}:**\n\n1. **Pacing**: Consider tightening the dialogue in the opening paragraphs\n2. **Character Voice**: Elara's scientific precision could be emphasized more\n3. **Sensory Details**: Add more description of the ship's ambient sounds\n4. **Emotional Beat**: The transition from guilt to determination could be stronger\n\nThese suggestions would be generated by analyzing the scene through the LLM with full story context from the MCP server.`;
      } else if (assistantType === 'suggest') {
        mockResponse = `**Story Suggestions:**\n\n**Plot Development:**\n- Alice's sophisticated block-building moment could foreshadow later abilities\n- McCarran's investigation could intersect with Elara's research\n- The shimmer drugs might be connected to the cellular enhancement\n\n**Character Arcs:**\n- Elara needs a moment of breakthrough in her research\n- McCarran should discover something that challenges his assumptions\n- AURORA's role as observer could become more active\n\n**Themes to Develop:**\n- Cost of progress vs. benefit to humanity\n- Vitae in Universum mission vs. individual suffering\n- Trust in unknown/untested technology`;
      } else if (assistantType === 'analyze') {
        mockResponse = `**Continuity Analysis:**\n\n✓ **Timeline**: Events flow logically from Prologue through Interlude 1\n✓ **Character Behavior**: Elara's guilt and dedication remain consistent\n✓ **World Rules**: Tera Galactica's systems and scale stay coherent\n\n⚠ **Potential Issues:**\n- Alice's block-building moment needs follow-up\n- McCarran's two concussions in quick succession - check medical realism\n- Shimmer drug investigation closure feels rushed - may need expansion\n\n📊 **Story Health:**\n- Word Count: ~${dataStore.getStats().totalWordCount.toLocaleString()}\n- Active Plot Threads: 5 (Enhancement complications, drug investigation, mysterious arrival, Alice's abilities, ship-wide conspiracy)\n- Character Development: Strong for Elara and McCarran, moderate for supporting cast`;
      }

      if (customPrompt) {
        mockResponse += `\n\n**Addressing your specific question:**\n"${customPrompt}"\n\nThe LLM would provide a detailed response here based on full story context.`;
      }

      setResponse(mockResponse);
      setIsLoading(false);
    }, 1500);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-slate-900">Writing Assistant</h1>
        <p className="text-slate-600 mt-1">
          Get AI-powered help with writing, revision, and story development
        </p>
      </div>

      {/* Context Selection */}
      <div className="bg-white rounded-lg shadow-sm p-6 border border-slate-200 space-y-4">
        <h2 className="text-lg font-semibold text-slate-900">Select Context</h2>
        
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-2">
              Chapter
            </label>
            <select
              value={selectedChapter}
              onChange={(e) => handleChapterSelect(e.target.value)}
              className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            >
              <option value="">Select a chapter...</option>
              {chapters.map((chapter) => (
                <option key={chapter.id} value={chapter.id}>
                  {chapter.title}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 mb-2">
              Scene (Optional)
            </label>
            <select
              value={selectedScene}
              onChange={(e) => setSelectedScene(e.target.value)}
              disabled={!selectedChapter}
              className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 disabled:bg-slate-100"
            >
              <option value="">All scenes</option>
              {scenes.map((scene) => (
                <option key={scene.id} value={scene.id}>
                  {scene.title}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Assistant Type */}
      <div className="bg-white rounded-lg shadow-sm p-6 border border-slate-200 space-y-4">
        <h2 className="text-lg font-semibold text-slate-900">What do you need help with?</h2>
        
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          <button
            onClick={() => setAssistantType('continue')}
            className={`p-4 rounded-lg border-2 transition-colors ${
              assistantType === 'continue'
                ? 'border-blue-500 bg-blue-50 text-blue-700'
                : 'border-slate-200 hover:border-slate-300 text-slate-700'
            }`}
          >
            <div className="text-2xl mb-2">✍️</div>
            <div className="font-medium">Continue Writing</div>
            <div className="text-xs mt-1 opacity-75">Generate next paragraphs</div>
          </button>

          <button
            onClick={() => setAssistantType('revise')}
            className={`p-4 rounded-lg border-2 transition-colors ${
              assistantType === 'revise'
                ? 'border-blue-500 bg-blue-50 text-blue-700'
                : 'border-slate-200 hover:border-slate-300 text-slate-700'
            }`}
          >
            <div className="text-2xl mb-2">✨</div>
            <div className="font-medium">Revise</div>
            <div className="text-xs mt-1 opacity-75">Improvement suggestions</div>
          </button>

          <button
            onClick={() => setAssistantType('suggest')}
            className={`p-4 rounded-lg border-2 transition-colors ${
              assistantType === 'suggest'
                ? 'border-blue-500 bg-blue-50 text-blue-700'
                : 'border-slate-200 hover:border-slate-300 text-slate-700'
            }`}
          >
            <div className="text-2xl mb-2">💡</div>
            <div className="font-medium">Suggest Ideas</div>
            <div className="text-xs mt-1 opacity-75">Plot and character ideas</div>
          </button>

          <button
            onClick={() => setAssistantType('analyze')}
            className={`p-4 rounded-lg border-2 transition-colors ${
              assistantType === 'analyze'
                ? 'border-blue-500 bg-blue-50 text-blue-700'
                : 'border-slate-200 hover:border-slate-300 text-slate-700'
            }`}
          >
            <div className="text-2xl mb-2">🔍</div>
            <div className="font-medium">Analyze</div>
            <div className="text-xs mt-1 opacity-75">Check continuity</div>
          </button>
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-2">
            Custom Prompt (Optional)
          </label>
          <textarea
            value={customPrompt}
            onChange={(e) => setCustomPrompt(e.target.value)}
            placeholder="Add specific instructions or questions..."
            rows={3}
            className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
          />
        </div>

        <button
          onClick={handleGetAssistance}
          disabled={!selectedChapter || isLoading}
          className="w-full px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-slate-300 disabled:cursor-not-allowed font-medium transition-colors"
        >
          {isLoading ? 'Thinking...' : 'Get AI Assistance'}
        </button>
      </div>

      {/* Response */}
      {response && (
        <div className="bg-white rounded-lg shadow-sm p-6 border border-slate-200">
          <h2 className="text-lg font-semibold text-slate-900 mb-4 flex items-center gap-2">
            <span>🤖</span>
            AI Response
          </h2>
          <div className="prose prose-slate max-w-none">
            <div className="whitespace-pre-wrap text-slate-700">{response}</div>
          </div>
        </div>
      )}

      {/* MCP Integration Info */}
      <div className="bg-gradient-to-r from-purple-50 to-blue-50 rounded-lg p-6 border border-purple-200">
        <h2 className="text-xl font-semibold text-slate-900 mb-2 flex items-center gap-2">
          <span>🔌</span>
          MCP Integration
        </h2>
        <p className="text-slate-700 mb-4">
          This writing assistant uses the MCP (Model Context Protocol) to provide your story context to LLMs.
        </p>
        <div className="bg-white rounded-lg p-4 border border-purple-200 space-y-2">
          <div className="text-sm text-slate-700">
            <strong>Available Tools:</strong>
            <ul className="list-disc list-inside mt-2 space-y-1 text-slate-600">
              <li>get_story_context - Full story overview</li>
              <li>get_scene_context - Detailed scene information</li>
              <li>get_character_details - Character profiles</li>
              <li>search_story_content - Search across all content</li>
              <li>analyze_continuity - Check for plot holes</li>
            </ul>
          </div>
        </div>
        <div className="mt-4 text-sm text-slate-600">
          <p>
            <strong>To connect:</strong> Configure your LLM client (Claude Desktop, etc.) using the mcp-config.json file in the project root. The server provides complete story context including all chapters, characters, locations, notes, and commit history.
          </p>
        </div>
      </div>
    </div>
  );
}
